### PR TITLE
Add Case Study: Excel Functions with Blockspring

### PR DESCRIPTION
**Pull request by felixrieseberg**
Added a new case study describing how we integrated custom functions for Blockspring using Office Add-Ins (formerly known as OfficeJS).  I’d appreciate a quick review from the usual pros - maybe @vjrantal and @jmspring?

### CODE REVIEW

**Comment by bstark23** [comment]
Only thing I really noticed (grammatical error but also room for improvement in wording):
Maybe change - "This case study describes how turned the Blockspring addon into a modern Office Add-In and made it available in Excel 2015, Excel Online, and Excel for iPad."
To something like - "This case study describes how we collaboratively helped turn the Blockspring addon into a modern Office Add-In and made it available in Excel 2015, Excel Online, and Excel for iPad."

**Comment by jmspring** [comment]
Some edits --

"You can easily create a spreadsheet that searches Twitter for “#Windows10”, take all the names of people who wrote tweets, find their LinkedIn profiles, and run image analysis on their profile pics."

**Comment by jmspring** [comment]
Some edits:

You can easily create a spreadsheet that searches Twitter for “#Windows10”, take all the names of people who wrote tweets, find their LinkedIn profiles, and run image analysis on their profile pics. Or do anything else: Blockspring has thousands of functions at this point. This case study describes how turned the Blockspring addon into a modern Office Add-In and made it available in Excel 2015, Excel Online, and Excel for iPad.

to

You can easily create a spreadsheet that searches Twitter for “#Windows10”, take all the names of the people who wrote tweets, find their LinkedIn profiles, and run image analysis on their profile pics. Or do anything else. Blockspring has thousands of functions at this point. This case study describes how we helped turn the Blockspring addon into a modern Office Add-In and made it available in Excel 2015, Excel Online, and Excel for iPad.

---

Plugins for Office are not necessarily a new idea, but the old plugin model is gone - with Office now running on tablets and computers as well as on all major systems

to

Plugins for Office are not necessarily a new idea, but the old plugin model is gone - with Office now running on tablets and computers as well as on all major operating systems

---
Overview of the Solution

*** this needs to be popped out as a header, it shows up at the end of a paragraph now
---

The add-in now features a simple flow: Select a function, insert the function call into a cell, and execute the calculation by clicking a "Run function in Current Cell" button.

*** "Select a function" should either be lower case, or break each out into a list?
---
 one has to observe the current user selection and read containing data.

to

one has to observe the current user selection and read the data therein.
---

We can now read function calls from selected cells, parse them, and kick of asynchronous computation on Blockspring’s servers.

to

We can now read function calls from the selected cells, parse them, and kick off an asynchronous computation on Blockspring's servers.

---

For titles "Setting Cell Data", "Getting Cell Data", and "Creating a Named Binding" -- maybe add some formatting around them to call them out as labels to the code snippets?

---

CODE BLOCK -- "Creating a Named Binding" has 4 space indents, the other two use 2 space indents

---
OfficeJS does currently not support custom functions - the old plugin model does, though. 

to

OfficeJS does not currently support custom functions unlike the old plugin model does.

---
"more powerful installations of Excel"

*** to you mean "more powerful" or "more recent"?

**Comment by felixrieseberg** [comment]
@bstark23, @jmspring, @vjrantal: Thanks for the review! I added all your proposed changes.

**Pull request merged**
