### PR TITLE
TechArticle Schema

### PR DESCRIPTION
**Pull request by stephbu**
Added schema labels for SEO goodness

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Neat! Could you quickly squash your commits?

**Comment by stephbu** [comment]
I split them into two genres - schema stuff, and still applying some markup tlc to the Azure Graph article

**Comment by felixrieseberg** [comment]
Awesome! I'll merge just as soon as you squashed your commits down (keeping the history clean and the repo small). Here's a quick how to: https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by stephbu** [comment]
Hey Felix, you probably missed the fact that I did already I squashed the other 4 commits into two different ones, 3 meta into 1, 1 article change.  Notionally they could be reverted independently.  I can crush them into one, but it feels a little wrong, and somewhat of a vanity thing only.  If I get time tomorrow I'll probably just revert the article change and submit it separately to meet vanity bar.

**Comment by felixrieseberg** [comment]
Hey, you probably just forgot to push it again - I'll find you on Slack :)

**Pull request closed without merging**
