### PR TITLE
updating to add images to home page and post page (for rallyteam article only)

### PR DESCRIPTION
**Pull request by SaraSp**

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Awesome stuff :clap:, but Travis is complaining about a missing `alt` attribute. You might also not want to commit the pic of your kids (they are pretty cute though). Also, you might want to squash your commits down to just one (which would be nice, but isn't required).

@tylergibson: Do you think we can do better here? I'm wondering if this could look better:

img_3249

**Comment by SaraSp** [comment]
removed test image.
and added alt tag.

**Comment by felixrieseberg** [comment]
Passes tests :rainbow:! Merging right away.

**Comment by tylergibson** [comment]
Thanks for putting an image in, I can massage it to fit better this evening :)




On Wed, Jul 22, 2015 at 1:47 PM -0700, "Felix Rieseberg" <notifications@github.com<mailto:notifications@github.com>> wrote:


Awesome stuff [:clap:] , but Travis is complaining about a missing alt attribute. You might also not want to commit the pic of your kids (they are pretty cute though). Also, you might want to squash your commits down to just one (which would be nice, but isn't required).

@tylergibson<https://github.com/tylergibson>: Do you think we can do better here? I'm wondering if this could look better:

[img_3249]<https://cloud.githubusercontent.com/assets/1426799/8836854/ed08aab0-3088-11e5-819c-d7ad375a0c1d.PNG>

-

**Comment by SaraSp** [comment]
Fyi...i fixed the alt tag and removed the test image if my kiddos.

Sara

Sent from my Windows Phone
________________________________

**Comment by felixrieseberg** [comment]
It's already merged :)

**Pull request merged**
